import type { Metadata } from 'next';
import { Readex_Pro } from 'next/font/google';

import '@/styles/globals.css';

import { cn } from '@/lib/utils';

import Providers from './providers';

const readexPro = Readex_Pro({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(readexPro.className, 'antialiased w-screen overflow-hidden')} cz-shortcut-listen="true">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
